import 'package:flutter/material.dart';
import 'package:world_time/services/world_time.dart';

class ChooseLocation extends StatefulWidget {
  const ChooseLocation({super.key});

  @override
  State<ChooseLocation> createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {
  
  List<WorldTime> locations = [
    WorldTime(location: 'Abidjan', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Abidjan'),
    WorldTime(location: 'Algiers', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Algiers'),
    WorldTime(location: 'Bissau', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Bissau'),
    WorldTime(location: 'Cairo', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Cairo'),
    WorldTime(location: 'Casablanca', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Casablanca'),
    WorldTime(location: 'Ceuta', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Ceuta'),
    WorldTime(location: 'El_Aaiun', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/El_Aaiun'),
    WorldTime(location: 'Johannesburg', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Johannesburg'),
    WorldTime(location: 'Juba', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Juba'),
    WorldTime(location: 'Khartoum', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Khartoum'),
    WorldTime(location: 'Lagos', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Lagos'),
    WorldTime(location: 'Maputo', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Maputo'),
    WorldTime(location: 'Monrovia', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Monrovia'),
    WorldTime(location: 'Nairobi', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Nairobi'),
    WorldTime(location: 'Ndjamena', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Ndjamena'),
    WorldTime(location: 'Sao_Tome', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Sao_Tome'),
    WorldTime(location: 'Tripoli', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Tripoli'),
    WorldTime(location: 'Tunis', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Tunis'),
    WorldTime(location: 'Windhoek', flag: 'https://www.countryflags.com/wp-content/uploads/arab-league-flag-jpg-xl.jpg', url: 'Africa/Windhoek'),
    WorldTime(location: 'Adak', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Adak'),
    WorldTime(location: 'Anchorage', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Anchorage'),
    WorldTime(location: 'Araguaina', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Araguaina'),
    WorldTime(location: 'Buenos_Aires', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Buenos_Aires'),
    WorldTime(location: 'Catamarca', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Catamarca'),
    WorldTime(location: 'Cordoba', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Cordoba'),
    WorldTime(location: 'Jujuy', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Jujuy'),
    WorldTime(location: 'La_Rioja', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/La_Rioja'),
    WorldTime(location: 'Mendoza', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Mendoza'),
    WorldTime(location: 'Rio_Gallegos', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Rio_Gallegos'),
    WorldTime(location: 'Salta', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Salta'),
    WorldTime(location: 'San_Juan', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/San_Juan'),
    WorldTime(location: 'San_Luis', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/San_Luis'),
    WorldTime(location: 'Tucuman', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Tucuman'),
    WorldTime(location: 'Ushuaia', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Argentina/Ushuaia'),
    WorldTime(location: 'Asuncion', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Asuncion'),
    WorldTime(location: 'Bahia', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Bahia'),
    WorldTime(location: 'Bahia_Banderas', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Bahia_Banderas'),
    WorldTime(location: 'Barbados', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Barbados'),
    WorldTime(location: 'Belem', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Belem'),
    WorldTime(location: 'Belize', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Belize'),
    WorldTime(location: 'Boa_Vista', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Boa_Vista'),
    WorldTime(location: 'Bogota', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Bogota'),
    WorldTime(location: 'Boise', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Boise'),
    WorldTime(location: 'Cambridge_Bay', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Cambridge_Bay'),
    WorldTime(location: 'Campo_Grande', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Campo_Grande'),
    WorldTime(location: 'Cancun', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Cancun'),
    WorldTime(location: 'Caracas', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Caracas'),
    WorldTime(location: 'Cayenne', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Cayenne'),
    WorldTime(location: 'Chicago', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Chicago'),
    WorldTime(location: 'Chihuahua', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Chihuahua'),
    WorldTime(location: 'Ciudad_Juarez', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Ciudad_Juarez'),
    WorldTime(location: 'Costa_Rica', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Costa_Rica'),
    WorldTime(location: 'Cuiaba', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Cuiaba'),
    WorldTime(location: 'Danmarkshavn', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Danmarkshavn'),
    WorldTime(location: 'Dawson', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Dawson'),
    WorldTime(location: 'Dawson_Creek', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Dawson_Creek'),
    WorldTime(location: 'Denver', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Denver'),
    WorldTime(location: 'Detroit', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Detroit'),
    WorldTime(location: 'Edmonton', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Edmonton'),
    WorldTime(location: 'Eirunepe', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Eirunepe'),
    WorldTime(location: 'El_Salvador', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/El_Salvador'),
    WorldTime(location: 'Fort_Nelson', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Fort_Nelson'),
    WorldTime(location: 'Fortaleza', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Fortaleza'),
    WorldTime(location: 'Glace_Bay', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Glace_Bay'),
    WorldTime(location: 'Goose_Bay', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Goose_Bay'),
    WorldTime(location: 'Grand_Turk', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Grand_Turk'),
    WorldTime(location: 'Guatemala', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Guatemala'),
    WorldTime(location: 'Guayaquil', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Guayaquil'),
    WorldTime(location: 'Guyana', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Guyana'),
    WorldTime(location: 'Halifax', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Halifax'),
    WorldTime(location: 'Havana', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Havana'),
    WorldTime(location: 'Hermosillo', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Hermosillo'),
    WorldTime(location: 'Indianapolis', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Indianapolis'),
    WorldTime(location: 'Knox', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Knox'),
    WorldTime(location: 'Marengo', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Marengo'),
    WorldTime(location: 'Petersburg', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Petersburg'),
    WorldTime(location: 'Tell_City', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Tell_City'),
    WorldTime(location: 'Vevay', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Vevay'),
    WorldTime(location: 'Vincennes', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Vincennes'),
    WorldTime(location: 'Winamac', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Indiana/Winamac'),
    WorldTime(location: 'Inuvik', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Inuvik'),
    WorldTime(location: 'Iqaluit', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Iqaluit'),
    WorldTime(location: 'Jamaica', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Jamaica'),
    WorldTime(location: 'Juneau', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Juneau'),
    WorldTime(location: 'Louisville', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Kentucky/Louisville'),
    WorldTime(location: 'Monticello', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Kentucky/Monticello'),
    WorldTime(location: 'La_Paz', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/La_Paz'),
    WorldTime(location: 'Lima', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Lima'),
    WorldTime(location: 'Los_Angeles', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Los_Angeles'),
    WorldTime(location: 'Maceio', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Maceio'),
    WorldTime(location: 'Managua', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Managua'),
    WorldTime(location: 'Manaus', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Manaus'),
    WorldTime(location: 'Martinique', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Martinique'),
    WorldTime(location: 'Matamoros', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Matamoros'),
    WorldTime(location: 'Mazatlan', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Mazatlan'),
    WorldTime(location: 'Menominee', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Menominee'),
    WorldTime(location: 'Merida', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Merida'),
    WorldTime(location: 'Metlakatla', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Metlakatla'),
    WorldTime(location: 'Mexico_City', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Mexico_City'),
    WorldTime(location: 'Miquelon', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Miquelon'),
    WorldTime(location: 'Moncton', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Moncton'),
    WorldTime(location: 'Monterrey', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Monterrey'),
    WorldTime(location: 'Montevideo', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Montevideo'),
    WorldTime(location: 'New_York', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/New_York'),
    WorldTime(location: 'Nome', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Nome'),
    WorldTime(location: 'Noronha', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Noronha'),
    WorldTime(location: 'Beulah', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/North_Dakota/Beulah'),
    WorldTime(location: 'Center', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/North_Dakota/Center'),
    WorldTime(location: 'New_Salem', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/North_Dakota/New_Salem'),
    WorldTime(location: 'Nuuk', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Nuuk'),
    WorldTime(location: 'Ojinaga', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Ojinaga'),
    WorldTime(location: 'Panama', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Panama'),
    WorldTime(location: 'Paramaribo', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Paramaribo'),
    WorldTime(location: 'Phoenix', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Phoenix'),
    WorldTime(location: 'Prince', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Port-au-Prince'),
    WorldTime(location: 'Porto_Velho', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Porto_Velho'),
    WorldTime(location: 'Puerto_Rico', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Puerto_Rico'),
    WorldTime(location: 'Punta_Arenas', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Punta_Arenas'),
    WorldTime(location: 'Rankin_Inlet', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Rankin_Inlet'),
    WorldTime(location: 'Recife', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Recife'),
    WorldTime(location: 'Regina', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Regina'),
    WorldTime(location: 'Resolute', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Resolute'),
    WorldTime(location: 'Rio_Branco', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Rio_Branco'),
    WorldTime(location: 'Santarem', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Santarem'),
    WorldTime(location: 'Santiago', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Santiago'),
    WorldTime(location: 'Santo_Domingo', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Santo_Domingo'),
    WorldTime(location: 'Sao_Paulo', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Sao_Paulo'),
    WorldTime(location: 'Scoresbysund', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Scoresbysund'),
    WorldTime(location: 'Sitka', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Sitka'),
    WorldTime(location: 'St_Johns', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/St_Johns'),
    WorldTime(location: 'Swift_Current', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Swift_Current'),
    WorldTime(location: 'Tegucigalpa', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Tegucigalpa'),
    WorldTime(location: 'Thule', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Thule'),
    WorldTime(location: 'Tijuana', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Tijuana'),
    WorldTime(location: 'Toronto', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Toronto'),
    WorldTime(location: 'Vancouver', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Vancouver'),
    WorldTime(location: 'Whitehorse', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Whitehorse'),
    WorldTime(location: 'Winnipeg', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Winnipeg'),
    WorldTime(location: 'Yakutat', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'America/Yakutat'),
    WorldTime(location: 'Casey', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'Antarctica/Casey'),
    WorldTime(location: 'Davis', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'Antarctica/Davis'),
    WorldTime(location: 'Macquarie', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'Antarctica/Macquarie'),
    WorldTime(location: 'Mawson', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'Antarctica/Mawson'),
    WorldTime(location: 'Palmer', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'Antarctica/Palmer'),
    WorldTime(location: 'Rothera', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'Antarctica/Rothera'),
    WorldTime(location: 'Troll', flag: 'https://www.countryflags.com/wp-content/uploads/united-states-of-america-flag-png-large.png', url: 'Antarctica/Troll'),
    WorldTime(location: 'Almaty', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Almaty'),
    WorldTime(location: 'Amman', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Amman'),
    WorldTime(location: 'Anadyr', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Anadyr'),
    WorldTime(location: 'Aqtau', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Aqtau'),
    WorldTime(location: 'Aqtobe', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Aqtobe'),
    WorldTime(location: 'Ashgabat', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Ashgabat'),
    WorldTime(location: 'Atyrau', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Atyrau'),
    WorldTime(location: 'Baghdad', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Baghdad'),
    WorldTime(location: 'Baku', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Baku'),
    WorldTime(location: 'Bangkok', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Bangkok'),
    WorldTime(location: 'Barnaul', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Barnaul'),
    WorldTime(location: 'Beirut', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Beirut'),
    WorldTime(location: 'Bishkek', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Bishkek'),
    WorldTime(location: 'Chita', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Chita'),
    WorldTime(location: 'Choibalsan', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Choibalsan'),
    WorldTime(location: 'Colombo', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Colombo'),
    WorldTime(location: 'Damascus', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Damascus'),
    WorldTime(location: 'Dhaka', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Dhaka'),
    WorldTime(location: 'Dili', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Dili'),
    WorldTime(location: 'Dubai', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Dubai'),
    WorldTime(location: 'Dushanbe', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Dushanbe'),
    WorldTime(location: 'Famagusta', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Famagusta'),
    WorldTime(location: 'Gaza', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Gaza'),
    WorldTime(location: 'Hebron', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Hebron'),
    WorldTime(location: 'Ho_Chi_Minh', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Ho_Chi_Minh'),
    WorldTime(location: 'Hong_Kong', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Hong_Kong'),
    WorldTime(location: 'Hovd', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Hovd'),
    WorldTime(location: 'Irkutsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Irkutsk'),
    WorldTime(location: 'Jakarta', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Jakarta'),
    WorldTime(location: 'Jayapura', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Jayapura'),
    WorldTime(location: 'Jerusalem', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Jerusalem'),
    WorldTime(location: 'Kabul', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Kabul'),
    WorldTime(location: 'Kamchatka', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Kamchatka'),
    WorldTime(location: 'Karachi', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Karachi'),
    WorldTime(location: 'Kathmandu', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Kathmandu'),
    WorldTime(location: 'Khandyga', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Khandyga'),
    WorldTime(location: 'Kolkata', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Kolkata'),
    WorldTime(location: 'Krasnoyarsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Krasnoyarsk'),
    WorldTime(location: 'Kuching', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Kuching'),
    WorldTime(location: 'Macau', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Macau'),
    WorldTime(location: 'Magadan', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Magadan'),
    WorldTime(location: 'Makassar', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Makassar'),
    WorldTime(location: 'Manila', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Manila'),
    WorldTime(location: 'Nicosia', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Nicosia'),
    WorldTime(location: 'Novokuznetsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Novokuznetsk'),
    WorldTime(location: 'Novosibirsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Novosibirsk'),
    WorldTime(location: 'Omsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Omsk'),
    WorldTime(location: 'Oral', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Oral'),
    WorldTime(location: 'Pontianak', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Pontianak'),
    WorldTime(location: 'Pyongyang', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Pyongyang'),
    WorldTime(location: 'Qatar', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Qatar'),
    WorldTime(location: 'Qostanay', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Qostanay'),
    WorldTime(location: 'Qyzylorda', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Qyzylorda'),
    WorldTime(location: 'Riyadh', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Riyadh'),
    WorldTime(location: 'Sakhalin', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Sakhalin'),
    WorldTime(location: 'Samarkand', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Samarkand'),
    WorldTime(location: 'Seoul', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Seoul'),
    WorldTime(location: 'Shanghai', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Shanghai'),
    WorldTime(location: 'Singapore', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Singapore'),
    WorldTime(location: 'Srednekolymsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Srednekolymsk'),
    WorldTime(location: 'Taipei', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Taipei'),
    WorldTime(location: 'Tashkent', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Tashkent'),
    WorldTime(location: 'Tbilisi', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Tbilisi'),
    WorldTime(location: 'Tehran', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Tehran'),
    WorldTime(location: 'Thimphu', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Thimphu'),
    WorldTime(location: 'Tokyo', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Tokyo'),
    WorldTime(location: 'Tomsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Tomsk'),
    WorldTime(location: 'Ulaanbaatar', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Ulaanbaatar'),
    WorldTime(location: 'Urumqi', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Urumqi'),
    WorldTime(location: 'Nera', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Ust-Nera'),
    WorldTime(location: 'Vladivostok', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Vladivostok'),
    WorldTime(location: 'Yakutsk', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Yakutsk'),
    WorldTime(location: 'Yangon', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Yangon'),
    WorldTime(location: 'Yekaterinburg', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Yekaterinburg'),
    WorldTime(location: 'Yerevan', flag: 'https://www.countryflags.com/wp-content/uploads/china-flag-png-large.png', url: 'Asia/Yerevan'),
    WorldTime(location: 'Azores', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/Azores'),
    WorldTime(location: 'Bermuda', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/Bermuda'),
    WorldTime(location: 'Canary', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/Canary'),
    WorldTime(location: 'Cape_Verde', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/Cape_Verde'),
    WorldTime(location: 'Faroe', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/Faroe'),
    WorldTime(location: 'Madeira', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/Madeira'),
    WorldTime(location: 'South_Georgia', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/South_Georgia'),
    WorldTime(location: 'Stanley', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Atlantic/Stanley'),
    WorldTime(location: 'Adelaide', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Adelaide'),
    WorldTime(location: 'Brisbane', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Brisbane'),
    WorldTime(location: 'Broken_Hill', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Broken_Hill'),
    WorldTime(location: 'Darwin', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Darwin'),
    WorldTime(location: 'Eucla', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Eucla'),
    WorldTime(location: 'Hobart', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Hobart'),
    WorldTime(location: 'Lindeman', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Lindeman'),
    WorldTime(location: 'Lord_Howe', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Lord_Howe'),
    WorldTime(location: 'Melbourne', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Melbourne'),
    WorldTime(location: 'Perth', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Perth'),
    WorldTime(location: 'Sydney', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Australia/Sydney'),
    WorldTime(location: 'CET', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'CET'),
    WorldTime(location: 'CST6CDT', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'CST6CDT'),
    WorldTime(location: 'EET', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'EET'),
    WorldTime(location: 'EST', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'EST'),
    WorldTime(location: 'EST5EDT', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'EST5EDT'),
    WorldTime(location: 'GMT', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT'),
    WorldTime(location: '1', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+1'),
    WorldTime(location: '10', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+10'),
    WorldTime(location: '11', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+11'),
    WorldTime(location: '12', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+12'),
    WorldTime(location: '2', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+2'),
    WorldTime(location: '3', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+3'),
    WorldTime(location: '4', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+4'),
    WorldTime(location: '5', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+5'),
    WorldTime(location: '6', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+6'),
    WorldTime(location: '7', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+7'),
    WorldTime(location: '8', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+8'),
    WorldTime(location: '9', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT+9'),
    WorldTime(location: '1', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-1'),
    WorldTime(location: '10', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-10'),
    WorldTime(location: '11', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-11'),
    WorldTime(location: '12', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-12'),
    WorldTime(location: '13', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-13'),
    WorldTime(location: '14', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-14'),
    WorldTime(location: '2', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-2'),
    WorldTime(location: '3', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-3'),
    WorldTime(location: '4', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-4'),
    WorldTime(location: '5', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-5'),
    WorldTime(location: '6', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-6'),
    WorldTime(location: '7', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-7'),
    WorldTime(location: '8', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-8'),
    WorldTime(location: '9', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/GMT-9'),
    WorldTime(location: 'UTC', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Etc/UTC'),
    WorldTime(location: 'Andorra', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Andorra'),
    WorldTime(location: 'Astrakhan', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Astrakhan'),
    WorldTime(location: 'Athens', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Athens'),
    WorldTime(location: 'Belgrade', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Belgrade'),
    WorldTime(location: 'Berlin', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Berlin'),
    WorldTime(location: 'Brussels', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Brussels'),
    WorldTime(location: 'Bucharest', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Bucharest'),
    WorldTime(location: 'Budapest', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Budapest'),
    WorldTime(location: 'Chisinau', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Chisinau'),
    WorldTime(location: 'Dublin', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Dublin'),
    WorldTime(location: 'Gibraltar', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Gibraltar'),
    WorldTime(location: 'Helsinki', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Helsinki'),
    WorldTime(location: 'Istanbul', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Istanbul'),
    WorldTime(location: 'Kaliningrad', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Kaliningrad'),
    WorldTime(location: 'Kirov', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Kirov'),
    WorldTime(location: 'Kyiv', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Kyiv'),
    WorldTime(location: 'Lisbon', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Lisbon'),
    WorldTime(location: 'London', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/London'),
    WorldTime(location: 'Madrid', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Madrid'),
    WorldTime(location: 'Malta', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Malta'),
    WorldTime(location: 'Minsk', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Minsk'),
    WorldTime(location: 'Moscow', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Moscow'),
    WorldTime(location: 'Paris', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Paris'),
    WorldTime(location: 'Prague', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Prague'),
    WorldTime(location: 'Riga', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Riga'),
    WorldTime(location: 'Rome', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Rome'),
    WorldTime(location: 'Samara', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Samara'),
    WorldTime(location: 'Saratov', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Saratov'),
    WorldTime(location: 'Simferopol', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Simferopol'),
    WorldTime(location: 'Sofia', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Sofia'),
    WorldTime(location: 'Tallinn', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Tallinn'),
    WorldTime(location: 'Tirane', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Tirane'),
    WorldTime(location: 'Ulyanovsk', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Ulyanovsk'),
    WorldTime(location: 'Vienna', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Vienna'),
    WorldTime(location: 'Vilnius', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Vilnius'),
    WorldTime(location: 'Volgograd', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Volgograd'),
    WorldTime(location: 'Warsaw', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Warsaw'),
    WorldTime(location: 'Zurich', flag: 'https://www.countryflags.com/wp-content/uploads/europe-flag-jpg-xl.jpg', url: 'Europe/Zurich'),
    WorldTime(location: 'HST', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'HST'),
    WorldTime(location: 'Chagos', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Indian/Chagos'),
    WorldTime(location: 'Maldives', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Indian/Maldives'),
    WorldTime(location: 'Mauritius', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Indian/Mauritius'),
    WorldTime(location: 'MET', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'MET'),
    WorldTime(location: 'MST', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'MST'),
    WorldTime(location: 'MST7MDT', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'MST7MDT'),
    WorldTime(location: 'PST8PDT', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'PST8PDT'),
    WorldTime(location: 'Apia', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Apia'),
    WorldTime(location: 'Auckland', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Auckland'),
    WorldTime(location: 'Bougainville', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Bougainville'),
    WorldTime(location: 'Chatham', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Chatham'),
    WorldTime(location: 'Easter', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Easter'),
    WorldTime(location: 'Efate', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Efate'),
    WorldTime(location: 'Fakaofo', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Fakaofo'),
    WorldTime(location: 'Fiji', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Fiji'),
    WorldTime(location: 'Galapagos', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Galapagos'),
    WorldTime(location: 'Gambier', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Gambier'),
    WorldTime(location: 'Guadalcanal', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Guadalcanal'),
    WorldTime(location: 'Guam', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Guam'),
    WorldTime(location: 'Honolulu', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Honolulu'),
    WorldTime(location: 'Kanton', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Kanton'),
    WorldTime(location: 'Kiritimati', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Kiritimati'),
    WorldTime(location: 'Kosrae', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Kosrae'),
    WorldTime(location: 'Kwajalein', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Kwajalein'),
    WorldTime(location: 'Marquesas', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Marquesas'),
    WorldTime(location: 'Nauru', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Nauru'),
    WorldTime(location: 'Niue', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Niue'),
    WorldTime(location: 'Norfolk', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Norfolk'),
    WorldTime(location: 'Noumea', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Noumea'),
    WorldTime(location: 'Pago_Pago', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Pago_Pago'),
    WorldTime(location: 'Palau', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Palau'),
    WorldTime(location: 'Pitcairn', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Pitcairn'),
    WorldTime(location: 'Port_Moresby', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Port_Moresby'),
    WorldTime(location: 'Rarotonga', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Rarotonga'),
    WorldTime(location: 'Tahiti', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Tahiti'),
    WorldTime(location: 'Tarawa', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Tarawa'),
    WorldTime(location: 'Tongatapu', flag: 'https://www.countryflags.com/wp-content/uploads/somalia-flag-png-large.png', url: 'Pacific/Tongatapu'),
  ];

  void updateTime(index) async {
    WorldTime instance = locations[index];
    await instance.getTime();
    Navigator.pop(context, {
      'time': instance.time,
      'location': instance.location,
      'flag': instance.flag,
      'isDayTime': instance.isDayTime,
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        iconTheme: IconThemeData(
          color: Colors.white,
        ),
        backgroundColor: Colors.blue[900],
        centerTitle: true,
        title: Text('Choose Location',
          style: TextStyle(
            color: Colors.white,
          ),
        ),
      ),
      body: ListView.builder(
        itemCount: locations.length,
          itemBuilder: (context, index) {
            return Padding(
              padding: const EdgeInsets.symmetric(vertical: 1, horizontal: 4),
              child: Card(
                child: ListTile(
                  onTap: () {
                    updateTime(index);
                  },
                  title: Text(locations[index].location),
                  leading: CircleAvatar(
                    backgroundImage: NetworkImage(locations[index].flag),
                  ),
                ),
              ),
            );
          }
      ),
    );
  }
}
